In [4]:
import cv2 # computer vision
import numpy as np

In [5]:
# 이미지 불러오기
img1 = cv2.imread("images/matplot.jpg", cv2.IMREAD_UNCHANGED)
img2 = cv2.imread("images/matplot.jpg", cv2.IMREAD_GRAYSCALE)
img3 = cv2.imread("images/matplot.jpg", cv2.IMREAD_COLOR)

In [6]:
# 이미지 출력(나타내기)
cv2.imshow('image2', img2)
cv2.waitKey(0) # 다음 입력이 들어오기 전까지 띄어놓음
cv2.destroyAllWindows() # 키를 누르면 이미지 창이 닫힘

In [7]:
cv2.imwrite("images/result_matplot1.jpg", img1)
cv2.imwrite("images/result_matplot2.jpg", img2)
cv2.imwrite("images/result_matplot3.jpg", img3)

True

In [8]:
img2

array([[187, 189, 185, ..., 186, 184, 183],
       [186, 189, 185, ..., 187, 185, 184],
       [186, 189, 185, ..., 187, 187, 186],
       ...,
       [120, 120, 113, ..., 209, 207, 207],
       [112, 107, 102, ..., 184, 188, 193],
       [116, 106, 102, ..., 143, 141, 145]], dtype=uint8)

In [8]:
img1[:, :, 0] # [:, :, 0], [:, :, 1], [:, :, 2] (r, g, b)

array([[185, 187, 183, ..., 184, 182, 181],
       [184, 187, 183, ..., 185, 183, 182],
       [184, 187, 183, ..., 185, 185, 184],
       ...,
       [111, 109, 102, ..., 214, 212, 212],
       [103,  96,  91, ..., 189, 193, 198],
       [107,  95,  91, ..., 148, 146, 150]], dtype=uint8)

In [10]:
x = np.array([1, 3, 5])
print(x)

[1 3 5]


In [9]:
x1 = np.array([[1, 3, 5], [2, 4, 6]])
print(x1)

[[1 3 5]
 [2 4 6]]


In [11]:
y1 = x1.reshape(1, 6)
print(y1)

[[1 3 5 2 4 6]]


print(x.mean())
print(x1.mean())

In [15]:
print(img2.shape)

(300, 240)


In [16]:
print(img3.shape)

(300, 240, 3)


In [18]:
x2 = np.ones([2, 6])
print(x2)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [22]:
x2 = np.zeros([2, 6]) + 137
print(x2)

[[137. 137. 137. 137. 137. 137.]
 [137. 137. 137. 137. 137. 137.]]


In [26]:
x3 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(x3)
print(x3[1, 2]) # 행 열로 접근

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
7


In [27]:
print(x3[0, :])

[1 2 3 4]


In [30]:
img1[:, :, 0]

array([[185, 187, 183, ..., 184, 182, 181],
       [184, 187, 183, ..., 185, 183, 182],
       [184, 187, 183, ..., 185, 185, 184],
       ...,
       [111, 109, 102, ..., 214, 212, 212],
       [103,  96,  91, ..., 189, 193, 198],
       [107,  95,  91, ..., 148, 146, 150]], dtype=uint8)

In [33]:
# print(img1[0, 0, 0])
# print(img1[0, 0, 1])
# print(img1[0, 0, 2])
print(img1[0, 0, :]) # rgb color -> gray : (r+g+b)/3 
print(img1[0, 0, :].mean())

[185 188 186]
186.33333333333334


In [34]:
x4 = np.array([10, 20, 30, 40, 50, 60, 70])
result_x4 = x4 > 50
print(result_x4)

[False False False False False  True  True]


In [39]:
result = img2 > 200
print(result)
print(result.astype('uint8')) # 0 또는 1로 출력

[[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ...  True  True  True]
 [False False False ... False False False]
 [False False False ... False False False]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 1 1]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [42]:
x5 = np.random.randint(0, 256, (5, 4))
print(x5)

[[121  74 250 194]
 [ 18  31 112  78]
 [122  68 218  24]
 [ 11  52 201 213]
 [148  41  32 189]]
