In [12]:
# 1. 기본 라이브러리 불러오기
import cv2
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import NoNorm

In [13]:
# 2. (numpy) 샘플 이미지(sample) 생성하기
sample = np.array([[5,2,1], [6,9,3], [7,2,6]])
print(sample)

[[5 2 1]
 [6 9 3]
 [7 2 6]]


In [14]:
# default user parameter
n = 3

In [15]:
# 5. 일반화 된 연산자 함수 설계하기
def HomogeneityOperator(inp,n):
    k = np.uint8((n-1)/2)
    h,w = inp.shape
    
    inp_pad = np.zeros((h+2*k,w+2*k))
    inp_pad[k:h+k,k:w+k] = inp    
    
    out = np.zeros((h+2*k,w+2*k))
    for i in range(k,h+k):
        for j in range(k,w+k):
            temp = inp_pad[i-k:i+k+1,j-k:j+k+1]
            out[i,j] = np.max(np.abs([temp[1,1]- temp]))
    out = out[k:h+k,k:w+k]
    return np.uint8(out)

In [16]:
def DifferenceOperator(inp,n):
    k = np.uint8((n-1)/2)
    h,w = inp.shape
    
    inp_pad = np.zeros((h+2*k,w+2*k))
    inp_pad[k:h+k,k:w+k] = inp    
    
    out = np.zeros((h+2*k,w+2*k))
    for i in range(k,h+k):
        for j in range(k,w+k):
            temp = inp_pad[i-k:i+k+1,j-k:j+k+1]
            out[i,j] = np.max(np.abs([temp[0,0] - temp[2,2],\
                                      temp[0,1] - temp[2,1],\
                                      temp[0,2] - temp[2,0],\
                                      temp[1,0] - temp[1,2]]))
    out = out[k:h+k,k:w+k]
    return np.uint8(out)

In [17]:
inp = cv2.imread('images/Lenna.png', cv2.IMREAD_GRAYSCALE)
out1 = HomogeneityOperator(inp,n)
out2 = DifferenceOperator(inp,n)
print(np.max(out1))
print(np.max(out2))

220
220
