In [2]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# 2. (numpy) 필터 (mask) 생성하기
mask = np.array([[2,0,1], [0,1,2], [1,0,2]])
n = mask.shape[0]
print(mask)
print(n)

[[2 0 1]
 [0 1 2]
 [1 0 2]]
3


In [4]:
# 3. (numpy) 입력 이미지(inp) 생성하기
inp = np.array([[1,2,3], [0,1,2], [3,0,1]])
h,w = inp.shape
print(inp)
print((h,w))

[[1 2 3]
 [0 1 2]
 [3 0 1]]
(3, 3)


In [5]:
# 4. (numpy) 초기화된 출력 이미지(out) 생성하기
out = np.zeros((h,w))
print(out)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
# 5. inp 위치 [1,1] 픽셀값에 대해 컨볼루션을 수행하여, 결과 출력하기 (print)
out = np.zeros((h,w))
for x in range(0,n):
    for y in range(0,n):
        out[1,1] += inp[x,y] * mask[x,y]
print(out)

[[ 0.  0.  0.]
 [ 0. 15.  0.]
 [ 0.  0.  0.]]
