In [2]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

In [4]:
# 2. (numpy) 필터 (mask) 생성하기
mask = np.array([[1,2,3], [4,5,6], [7,8,9]])/45
n = mask.shape[0]
k = np.uint8((n-1)/2)
print(mask)
print(n)
print(k)

[[0.02222222 0.04444444 0.06666667]
 [0.08888889 0.11111111 0.13333333]
 [0.15555556 0.17777778 0.2       ]]
3
1


In [6]:
# 3. (numpy) 입력 이미지(inp) 생성하기
inp = cv2.imread('images/Lenna.png', cv2.IMREAD_GRAYSCALE)
h,w = inp.shape
print(inp)
print((h,w))

[[168 168 167 ... 171 177 154]
 [168 167 167 ... 174 182 158]
 [169 166 167 ... 150 132  99]
 ...
 [ 59  61  64 ...  82  98 102]
 [ 56  61  61 ...  95 110 111]
 [ 53  61  59 ... 106 116 118]]
(220, 220)


In [7]:
# 4. zero padding을 적용한 이미지(inp_pad) 생성하기
inp_pad = np.zeros((h+2*k, w+2*k))
inp_pad[k:h+k, k:w+k] = inp
print(inp_pad)

[[  0.   0.   0. ...   0.   0.   0.]
 [  0. 168. 168. ... 177. 154.   0.]
 [  0. 168. 167. ... 182. 158.   0.]
 ...
 [  0.  56.  61. ... 110. 111.   0.]
 [  0.  53.  61. ... 116. 118.   0.]
 [  0.   0.   0. ...   0.   0.   0.]]


In [8]:
# 5. numpy를 사용하여, 초기화된 출력 이미지 생성하기
out = np.zeros((h+2*k, w+2*k))
print(out)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [9]:
# 6. 컨볼루션을 수행하고 출력하기 (print)
for i in range(k, h+k):
    for j in range(k, w+k):
        temp = inp_pad[i-k:i+k+1, j-k:j+k+1]
        for x in range(0,n):
            for y in range(0,n):
                out[i,j] += temp[x,y]*mask[x,y]
out = out[k:h+k, k:w+k]
print(out[100,0])

85.35555555555555
